spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: banksDatabase
      authentication-database: admin
  demo-payments:
    openapi:
      dev-url: http://localhost:8080

  security:
    jwt:
      token:
        secret: ${JWT_SECRET:secret}
  mail:
    host: smtp.gmail.com
    protocol: smtp
    port: 587
    username: admdevpgames@gmail.com
    password: nleslrxuiusmbwzl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        from: admdevpgames@gmail.com
    from:
      name: support

  devtools:
    restart:
      enabled: false