spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: banksDatabase
      authentication-database: admin
  demo-payments:
    openapi:
      dev-url: http://localhost:8080
